# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yde-mont <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/24 15:02:11 by yde-mont          #+#    #+#              #
#    Updated: 2020/12/04 09:53:46 by yde-mont         ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

SRCS		= ft_atoi.c ft_bzero.c ft_calloc.c ft_isalnum.c ft_isalpha.c \
			  ft_isascii.c ft_isdigit.c ft_isprint.c ft_itoa.c ft_memccpy.c \
			  ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memmove.c ft_memset.c \
			  ft_putchar_fd.c ft_putendl_fd.c ft_putnbr_fd.c ft_putstr_fd.c \
			  ft_split.c ft_strchr.c ft_strdup.c ft_strjoin.c ft_strlcat.c \
			  ft_strlcpy.c ft_strlen.c ft_strmapi.c ft_strncmp.c ft_strnstr.c \
			  ft_strrchr.c ft_strtrim.c ft_substr.c ft_tolower.c ft_toupper.c 

OBJ			= ${SRCS:.c=.o}

SRCSB		= ft_lstadd_back.c ft_lstadd_front.c ft_lstclear.c ft_lstdelone.c \
			  ft_lstiter.c ft_lstlast.c ft_lstmap.c ft_lstnew.c ft_lstsize.c

OBJB		= ${SRCSB:.c=.o}

CFLAGS		= -Wall -Werror -Wextra 

CC			= gcc ${CFLAGS}

AR			= ar -rcs

NAME		= libft.a

%.o : %.c libft.h
	$(CC) -c $<

all:		${NAME}

$(NAME):	${OBJ}
				${AR} $@ ${OBJ}

bonus:		${OBJ} ${OBJB}
				${AR} ${NAME} ${OBJ} ${OBJB}  
clean:
				rm -f ${OBJ}

fclean:		clean
				rm -f ${NAME}

re:			clean all

.PHONY:		all bonus clean fclean re